apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasura
  name: hasura-headless
  namespace: itersocium
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: hasura
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasura
    hasuraService: custom
  name: hasura
  namespace: itersocium
spec:
  replicas: 1
  serviceName: hasura-headless
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      labels:
        app: hasura
    spec:
      containers:
      - image: hasura/graphql-engine:v2.5.1
        imagePullPolicy: IfNotPresent
        name: hasura
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: postgres://yugabyte:@yb-tservers.yb-demo.svc.cluster.local:5433/yugabyte
        - name: HASURA_GRAPHQL_DEV_MODE
          value: "true"
        - name: PG_DATABASE_URL
          value: postgres://yugabyte:@yb-tservers.yb-demo.svc.cluster.local:5433/yugabyte
        - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
          value: startup, http-log, webhook-log, websocket-log, query-log
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
  
