on:
  # push:
  #   branches: 
  #     - staging
  pull_request:     
    branches: 
      - staging

jobs:
  stage-app:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./IterSocium
    strategy:
      matrix:
        app: [managed]
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Setup Expo
        uses: expo/expo-github-action@v5
        with:
          expo-cache: true
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_TOKEN }}
      - name: Find cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files
      - name: Build packages
        run: yarn build
      - name: Publish to Expo
        working-directory: apps/${{ matrix.app }}
        run: expo publish --release-channel=pr-${{ github.event.number }}
      - name: Get deployment link
        run: echo "::set-output name=path::@bycedric/eas-monorepo-example?release-channel=pr-${{ github.event.number }}"
        id: expo
      - name: Comment deployment link
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: You can preview [`apps/${{ matrix.app }}` here](https://expo.io/${{ steps.expo.outputs.path }}).<br><br><a href="https://exp.host/${{ steps.expo.outputs.path }}"><img src="https://api.qrserver.com/v1/create-qr-code/?size=400x400&data=exp://exp.host/${{ steps.expo.outputs.path }}" height="200px" width="200px"></a>