# This is a basic workflow that is manually triggered

name: Manual cluster setup

on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  k8s-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      # GitHub Action reference: https://github.com/jupyterhub/action-k3s-helm
      - name: Start a local k8s cluster
        uses: jupyterhub/action-k3s-helm@v2
        with:
          # See available:
          # - k3s release channels at https://github.com/k3s-io/k3s/blob/HEAD/channel.yaml
          # - k3s versions at https://github.com/k3s-io/k3s/tags
          # - helm versions at https://github.com/helm/helm/tags
          k3s-channel: latest
          # k3s-version: v1.22.2+k3s1
          # helm-version: v3.7.0

      - name: Verify function of k8s, kubectl, and helm
        run: |
          echo "kubeconfig: $KUBECONFIG"
          kubectl version
          kubectl get pods --all-namespaces

          helm version
          helm list

      - name: Install YugabyteDB
        run: |
          helm repo add yugabytedb https://charts.yugabyte.com

          helm repo update

          kubectl create namespace itersocium

          helm install itersocium yugabytedb/yugabyte \
          --set resource.master.requests.cpu=0.5,resource.master.requests.memory=0.5Gi,\
          resource.tserver.requests.cpu=0.5,resource.tserver.requests.memory=0.5Gi,\
          replicas.master=1,replicas.tserver=1, --namespace itersocium

      - name: Apply / Add Hasura deployment
        run: |
          kubectl apply -f ./k8s/dev -n itersocium
      
      - name: Show Pods
        run: |

          kubectl get pods --namespace itersocium

      
